#!/usr/bin/env bash
# Install EvoDiff (with its MSA checkpoints) as a CLI on this project's PATH.
#
# EvoDiff (Alamdari et al., Nature Communications 2026 / bioRxiv 2023.09.11.556673, MIT) is the
# discrete-diffusion protein generator whose MSA variant EvoFlows §4.2 uses as a baseline. THEIR
# package and THEIR weights, because a hand-rolled MSATransformer would make the baseline ours to get
# weak, and a weak baseline is a free win for the model compared against it.
#
# NOT `uv add evodiff`: evodiff 1.1.2 requires `numpy<2.0,>=1.25` and installing it into .venv
# downgrades BOTH numpy (2.4.6 -> 1.26.4) and scipy (1.18.0 -> 1.17.1); numpy 1.26.4 also predates
# cp314 wheels, so on Python 3.14 it would be built from source too. The answer is the same one
# every conflicting third-party model gets here: its own env, on Python 3.12 for that numpy<2 reason.
#
# evodiff has no CLI, so the shim runs editjumps/core/evodiff_msa/evodiff_msa_runner.py — a *server*, because
# order-agnostic decoding needs one forward pass per position and reloading the checkpoint each time
# is not viable.
#
# TWO deliberate deviations from evodiff's documented install, both found by running it:
#  1. `setuptools<81`: evodiff/pretrained.py imports `pkg_resources` (to locate its bundled
#     checkpoint config), which setuptools 81 removed, so a current setuptools breaks the import.
#  2. torch is installed explicitly: evodiff does not declare it, so `pip install evodiff` reports
#     success and then `import evodiff` dies with ModuleNotFoundError. Remove only once upstream
#     declares it.
#
# The MSA checkpoint (~380 MB) is NOT downloaded here — evodiff fetches it from Zenodo record 8045076
# into torch's hub cache on first use, triggered by the smoke test. First run needs network.
#
# Usage: bash editjumps/core/evodiff_msa/install_evodiff.sh [python_version]   # default 3.12
set -euo pipefail

PYVER="${1:-3.12}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
VENV_BIN="$REPO_ROOT/.venv/bin"
EVODIFF_ENV="$REPO_ROOT/.evodiff_env"
RUNNER="$REPO_ROOT/editjumps/core/evodiff_msa/evodiff_msa_runner.py"

if [ ! -d "$VENV_BIN" ]; then
    echo "error: $VENV_BIN not found - run 'uv sync' first" >&2
    exit 1
fi
if ! command -v uv >/dev/null 2>&1; then
    echo "error: uv not found - see https://docs.astral.sh/uv/" >&2
    exit 1
fi

echo "creating isolated EvoDiff env at $EVODIFF_ENV (python $PYVER) ..."
# --clear to stay idempotent; --no-project so uv does not resolve against this repo's own project
# metadata (its dependency groups and lock) inside an env that exists only for evodiff + numpy<2.
# It is NOT about requires-python: pyproject.toml's floor is >=3.10, which $PYVER satisfies.
uv venv --clear --no-project --python "$PYVER" "$EVODIFF_ENV"

# evodiff is pinned for reproducibility. torch is NOT: it is undeclared upstream, nothing of ours
# shares this interpreter, and pinning it would only break platforms lacking that exact build.
#
# `--torch-backend=auto` is load-bearing on a GPU box, for the same reason repro.sky.yaml passes it
# when it reinstalls torch into .venv: the default PyPI wheel is built for the newest CUDA, and the
# SkyPilot GCP VMs ship driver 535 (CUDA 12.2). This env is NOT covered by the yaml's fix -- it has
# its own interpreter and its own torch -- and the gap was invisible because the smoke test below
# runs `--device cpu`. Measured: sky job 71 resolved torch 2.13.0+cu130 here, whose CUDA-13 build
# that driver cannot initialise, so `--device auto` in the runner fell back to CPU and the §4.2
# baseline ran 25x slower -- 54 minutes without finishing the first of 20 templates, against 2
# minutes per template on the GPU, with nvidia-smi reporting 0% utilisation and 0 MiB used the whole
# time. `auto` detects the driver via nvidia-smi and picks a matching build; with no nvidia-smi (a
# Mac dev box) it resolves to the CPU wheel, which is what that machine wants anyway.
echo "installing evodiff + torch (pulls a large wheel; this is the slow part) ..."
VIRTUAL_ENV="$EVODIFF_ENV" uv pip install --quiet --torch-backend=auto \
    "evodiff==1.1.2" torch "setuptools<81"

# What this env's torch can actually do, printed because the smoke test below cannot say it: it runs
# `--device cpu` on purpose (it has to pass on a Mac), so a GPU box whose torch silently cannot
# initialise CUDA looks exactly like a healthy one. The stage's own `--device auto` reads this.
"$EVODIFF_ENV/bin/python" -c \
    "import torch, torch.version as v; print(f'evodiff env: torch {torch.__version__} (built for cuda {v.cuda}), cuda_available={torch.cuda.is_available()}')"

# Shim: evodiff is a library, so forward to the runner rather than to an executable.
cat > "$VENV_BIN/evodiff-msa" <<SHIM
#!/usr/bin/env bash
# Auto-generated by editjumps/core/evodiff_msa/install_evodiff.sh - runs the EvoDiff-MSA server in its isolated env.
# The runner imports only stdlib + evodiff/torch/numpy, so numpy<2 never enters our .venv.
exec "$EVODIFF_ENV/bin/python" "$RUNNER" "\$@"
SHIM
chmod +x "$VENV_BIN/evodiff-msa"

# Smoke test: a real checkpoint load and forward pass, not --help. Every failure that matters
# (missing pkg_resources, a 404 from Zenodo, a state-dict key mismatch) is invisible until then.
echo "smoke-testing (downloads ~380 MB of weights on first run) ..."
if "$VENV_BIN/evodiff-msa" --self-test --device cpu; then
    echo "ok: evodiff-msa -> $EVODIFF_ENV/bin/python $RUNNER"
    echo
    echo "Next: make evodiff-baseline           # the budget-matched §4.2 baseline"
    echo "  or: make evodiff-baseline MODE=unconditional   # their own entry point, unmatched"
else
    echo "error: evodiff installed but the smoke test failed - run it manually to see why:" >&2
    echo "  $VENV_BIN/evodiff-msa --self-test --device cpu" >&2
    exit 1
fi
